apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-nodeapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-nodeapp
    app.kubernetes.io/part-of: my-application
  name: test-nodeapp
  namespace: karthik-jk
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: test-nodeapp
status:
  loadBalancer: {}
